name: Designite Workflow

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set build system
        id: set-build-system
        run: |
          if [[ -f pom.xml ]]; then
            echo "::set-output name=build-system::maven"
          elif [[ -f build.gradle ]]; then
            echo "::set-output name=build-system::gradle"
          else
            echo "Build system not found"
            exit 1
          fi
          
      - name: Set up JDK 21
        run: |
          echo "JAVA_HOME=/usr/lib/jvm/temurin-21-jdk-amd64" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

          echo "JAVA_VERSION=${java_version}" >> $GITHUB_ENV
          
      - name: Print Environment Variables
        run: |
          echo "Printing all environment variables:"
          printenv
      
      # - name: Build with Gradle
      #   run: |
      #     if [[ "${{ steps.set-build-system.outputs.build-system }}" == "gradle" ]]; then
      #       ./gradlew build
      #     fi
          
      # - name: Build with Maven
      #   run: |
      #     if [[ "${{ steps.set-build-system.outputs.build-system }}" == "maven" ]]; then
      #       mvn clean install -Dmaven.test.skip=true
      #     fi

      - name: Download DesigniteJava
        run: | 
          if [ -f .github/DesigniteJava.jar ]; then
            echo "DesigniteJava already present"
          else
            wget "https://www.designite-tools.com/assets/DesigniteJava.jar"
            mv "DesigniteJava.jar" ".github/"
          fi
      - name: Analyze project with DesigniteJava
        run: |
          java -jar .github/DesigniteJava.jar -o Designite_output -ci -repo $GITHUB_REPOSITORY -pat ${{ secrets.PAT }} -k ${{ secrets.D_KEY }}
          ls
      - name: Upload Designite results as artifact
        uses: actions/upload-artifact@v2
        with:
          name: DesigniteAnalysis
          path: Designite_output/DesigniteAnalysis.xml
      - name: Download DesigniteAnalysis artifact
        uses: actions/download-artifact@v2
        with:
          name: DesigniteAnalysis
          path: Designite_output
      - name: Send DesigniteAnalysis.xml to Analysis controller
        run: |
          curl -X POST -F 'file=@Designite_output/DesigniteAnalysis.xml' http://localhost:8080/analysis/${{github.repository_id}}/${{github.ref_name}}
